apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mqtt-demo-dev
resources:
  - ../../base
commonAnnotations:
  demo.environment: dev

patchesStrategicMerge:
  - keda-address-patch.yaml
