apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker-a-queue-scaler
spec:
  scaleTargetRef:
    name: worker-a
  pollingInterval: 10
  cooldownPeriod: 30
  minReplicaCount: 1
  maxReplicaCount: 6
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 30
          policies:
            - type: Percent
              value: 100
              periodSeconds: 15
            - type: Pods
              value: 2
              periodSeconds: 15
          selectPolicy: Max
  triggers:
    - type: redis
      metadata:
        address: redis:6379
        listName: queue:broker-a
        listLength: "10"
        activationListLength: "1"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker-b-queue-scaler
spec:
  scaleTargetRef:
    name: worker-b
  pollingInterval: 10
  cooldownPeriod: 30
  minReplicaCount: 1
  maxReplicaCount: 6
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 30
          policies:
            - type: Percent
              value: 100
              periodSeconds: 15
            - type: Pods
              value: 2
              periodSeconds: 15
          selectPolicy: Max
  triggers:
    - type: redis
      metadata:
        address: redis:6379
        listName: queue:broker-b
        listLength: "10"
        activationListLength: "1"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker-c-queue-scaler
spec:
  scaleTargetRef:
    name: worker-c
  pollingInterval: 10
  cooldownPeriod: 30
  minReplicaCount: 1
  maxReplicaCount: 6
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 30
          policies:
            - type: Percent
              value: 100
              periodSeconds: 15
            - type: Pods
              value: 2
              periodSeconds: 15
          selectPolicy: Max
  triggers:
    - type: redis
      metadata:
        address: redis:6379
        listName: queue:broker-c
        listLength: "10"
        activationListLength: "1"
