apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker-a-queue-scaler
spec:
  scaleTargetRef:
    name: worker-a
  pollingInterval: 15
  cooldownPeriod: 90
  minReplicaCount: 1
  maxReplicaCount: 3
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 30
          policies:
            - type: Pods
              value: 1
              periodSeconds: 30
          selectPolicy: Max
        scaleDown:
          stabilizationWindowSeconds: 120
          policies:
            - type: Percent
              value: 50
              periodSeconds: 30
            - type: Pods
              value: 1
              periodSeconds: 30
          selectPolicy: Min
  triggers:
    - type: redis
      metadata:
        address: redis:6379
        listName: queue:broker-a
        listLength: "10"
        activationListLength: "5"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker-b-queue-scaler
spec:
  scaleTargetRef:
    name: worker-b
  pollingInterval: 15
  cooldownPeriod: 90
  minReplicaCount: 1
  maxReplicaCount: 3
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 30
          policies:
            - type: Pods
              value: 1
              periodSeconds: 30
          selectPolicy: Max
        scaleDown:
          stabilizationWindowSeconds: 120
          policies:
            - type: Percent
              value: 50
              periodSeconds: 30
            - type: Pods
              value: 1
              periodSeconds: 30
          selectPolicy: Min
  triggers:
    - type: redis
      metadata:
        address: redis:6379
        listName: queue:broker-b
        listLength: "10"
        activationListLength: "5"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker-c-queue-scaler
spec:
  scaleTargetRef:
    name: worker-c
  pollingInterval: 15
  cooldownPeriod: 90
  minReplicaCount: 1
  maxReplicaCount: 3
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 30
          policies:
            - type: Pods
              value: 1
              periodSeconds: 30
          selectPolicy: Max
        scaleDown:
          stabilizationWindowSeconds: 120
          policies:
            - type: Percent
              value: 50
              periodSeconds: 30
            - type: Pods
              value: 1
              periodSeconds: 30
          selectPolicy: Min
  triggers:
    - type: redis
      metadata:
        address: redis:6379
        listName: queue:broker-c
        listLength: "10"
        activationListLength: "5"
