apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mqtt-demo-prod
  namespace: openshift-gitops
spec:
  destination:
    namespace: mqtt-demo-prod
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deploy/overlays/prod
    repoURL: https://github.com/h8x0rd/ocp-mqtt-redis.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
